#!/usr/bin/env Rscript
# main.R - Easy Proteomics Analysis Configuration
# Generated by the ezprot DeepSeek Harness plugin
# Organism: {{ORGANISM}}
# Created: {{DATE}}
#
# This file only defines the configuration and loads the pipeline.
# Steps are executed non-interactively through run.R:
#   Rscript run.R <step>
#   <step> = all | normalization | pca | batch-removal | dea | enrich | gsea

# ─────────────────────────────────────────────────────────────────────────────
# Input data files
# ─────────────────────────────────────────────────────────────────────────────
protein_expr_file <- "{{PROTEIN_EXPR_FILE}}"
sample_info_file  <- "{{SAMPLE_INFO_FILE}}"

# ─────────────────────────────────────────────────────────────────────────────
# Output directory for analysis results
# ─────────────────────────────────────────────────────────────────────────────
base_dir <- "{{OUTPUT_DIR}}"

# ─────────────────────────────────────────────────────────────────────────────
# Annotation databases (absolute paths managed by the plugin)
# ─────────────────────────────────────────────────────────────────────────────
go_background_file   <- "{{GO_BACKGROUND_FILE}}"
kegg_background_file <- "{{KEGG_BACKGROUND_FILE}}"

# ─────────────────────────────────────────────────────────────────────────────
# Normalization settings
# na_threshold: single value or c(low, high) for auto imputation selection
#   - single value: proteins with NA% above threshold are discarded
#   - c(low, high): NA < low → KNN, low ≤ NA < high → Perseus, NA ≥ high → discard
# ─────────────────────────────────────────────────────────────────────────────
na_threshold <- {{NA_THRESHOLD}}

# "global" (normalize all samples together) or "within_group"
normalization_method <- "{{NORMALIZATION_METHOD}}"

# TRUE = normalize using proteins detected in all samples
use_common_proteins_for_norm <- {{USE_COMMON_PROTEINS}}

# "auto" (uses na_threshold rules), "knn", or "perseus"
imputation_method <- "{{IMPUTATION_METHOD}}"

# ─────────────────────────────────────────────────────────────────────────────
# Fold change / p-value threshold settings
# fc_threshold_mode: "auto" (coverage analysis), "global", or "per_comparison"
# ─────────────────────────────────────────────────────────────────────────────
fc_threshold_mode    <- "{{FC_THRESHOLD_MODE}}"
global_fc_threshold  <- {{GLOBAL_FC_THRESHOLD}}

p_threshold_mode    <- "{{P_THRESHOLD_MODE}}"
global_p_threshold  <- {{GLOBAL_P_THRESHOLD}}

# ─────────────────────────────────────────────────────────────────────────────
# Custom color scheme (NULL = auto-generate colors per group)
# ─────────────────────────────────────────────────────────────────────────────
custom_colors <- NULL

# ─────────────────────────────────────────────────────────────────────────────
# Comparison groups: list of comparisons to perform
# Each comparison: list(control = "GroupA", treatment = "GroupB", name = "GroupB_vs_GroupA")
# Multiple groups: control = c("GroupA", "GroupB"); per-comparison thresholds: fc_threshold = 2
# ─────────────────────────────────────────────────────────────────────────────
comparisons <- {{COMPARISONS_LIST}}

# ─────────────────────────────────────────────────────────────────────────────
# Load pipeline (steps are dispatched by run.R)
# ─────────────────────────────────────────────────────────────────────────────
this_file <- tryCatch(
  normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])),
  error = function(e) NULL
)
if (!is.null(this_file)) setwd(dirname(this_file))

source("analysis_steps.R")
